# Generated by Django 5.2.3 on 2025-08-19 20:13

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Required. Valid email address.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        default=apps.users.models.generate_username,
                        help_text="Unique username (auto-generated if blank).",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, help_text="First name.", max_length=30
                    ),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, help_text="Last name.", max_length=30),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Uploaded profile picture.",
                        null=True,
                        upload_to=apps.users.models.profile_picture_upload_to,
                    ),
                ),
                (
                    "profile_picture_url",
                    models.URLField(
                        blank=True, help_text="OAuth profile picture URL.", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Designates if the user is active."
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="Designates access to admin site."
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, help_text="Active premium subscription."
                    ),
                ),
                (
                    "premium_expiry",
                    models.DateTimeField(
                        blank=True,
                        help_text="Premium subscription end date.",
                        null=True,
                    ),
                ),
                (
                    "google_id",
                    models.CharField(
                        blank=True,
                        help_text="Google OAuth ID.",
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Email notifications enabled."
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Account creation timestamp.",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        auto_now=True, help_text="Last login timestamp."
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups this user belongs to.",
                        related_name="custom_users",
                        related_query_name="custom_user",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_permissions",
                        related_query_name="custom_user",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-date_joined"],
                "indexes": [
                    models.Index(fields=["email"], name="users_custo_email_c80f75_idx"),
                    models.Index(
                        fields=["-date_joined"], name="users_custo_date_jo_ecd7c8_idx"
                    ),
                ],
            },
        ),
    ]
