# Generated by Django 5.2.3 on 2025-08-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("features", models.JSONField(default=dict)),
                ("max_links", models.IntegerField(default=5)),
                ("max_cards", models.IntegerField(default=1)),
                ("analytics_enabled", models.BooleanField(default=False)),
                ("custom_themes", models.BooleanField(default=False)),
            ],
        ),
    ]
