# Generated by Django 5.2.3 on 2025-08-25 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("view", "Profile View"), ("click", "Link Click")],
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True, max_length=500)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "avatar_type",
                    models.CharField(
                        choices=[
                            ("initials", "Initials"),
                            ("emoji", "Emoji"),
                            ("image", "Image"),
                        ],
                        default="initials",
                        max_length=20,
                    ),
                ),
                ("avatar_value", models.CharField(max_length=100)),
                ("primary_color", models.CharField(default="#9333EA", max_length=7)),
                ("secondary_color", models.CharField(default="#3B82F6", max_length=7)),
                ("background_style", models.CharField(default="solid", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("minimal", "Minimal"),
                            ("founder", "Founder/Entrepreneur"),
                            ("creator", "Content Creator"),
                            ("developer", "Developer"),
                            ("business", "Business Professional"),
                            ("artist", "Artist/Designer"),
                            ("startup", "Startup Team"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("default_config", models.JSONField(default=dict)),
                ("is_premium", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CustomDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=100, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("ssl_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(max_length=500)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("custom_icon", models.CharField(blank=True, max_length=10)),
                ("custom_color", models.CharField(blank=True, max_length=7)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_featured", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LinkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=50)),
                ("icon_name", models.CharField(max_length=50)),
                ("color", models.CharField(default="#6B7280", max_length=7)),
                ("url_pattern", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("social", "Social Media"),
                            ("contact", "Contact"),
                            ("work", "Work"),
                            ("creative", "Creative"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
