# Generated by Django 5.2.3 on 2025-08-25 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="analytics",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="cards.card",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cards.cardtemplate"
            ),
        ),
        migrations.AddField(
            model_name="customdomain",
            name="card",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_domain",
                to="cards.card",
            ),
        ),
        migrations.AddField(
            model_name="link",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="cards.card",
            ),
        ),
        migrations.AddField(
            model_name="analytics",
            name="link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cards.link",
            ),
        ),
        migrations.AddField(
            model_name="link",
            name="link_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cards.linktype"
            ),
        ),
        migrations.AddIndex(
            model_name="analytics",
            index=models.Index(
                fields=["card", "action", "-timestamp"],
                name="cards_analy_card_id_4a76e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analytics",
            index=models.Index(
                fields=["timestamp"], name="cards_analy_timesta_8de6c4_idx"
            ),
        ),
    ]
