# Generated by Django 5.2.3 on 2025-08-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="avatar_value",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="card",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cards.cardtemplate",
            ),
        ),
    ]
