# Generated by Django 5.2.3 on 2025-08-25 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_alter_card_avatar_value_alter_card_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="link_type",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cards.linktype",
            ),
        ),
    ]
