# Generated by Django 5.2.3 on 2025-08-25 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_alter_link_link_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="link_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cards.linktype",
            ),
        ),
    ]
