# Generated by Django 5.2.3 on 2025-08-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_alter_link_link_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardtemplate",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
