# Generated by Django 5.2.3 on 2025-08-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_alter_cardtemplate_display_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="cardtemplate",
            name="description",
        ),
        migrations.RemoveField(
            model_name="linktype",
            name="color",
        ),
        migrations.RemoveField(
            model_name="linktype",
            name="icon_name",
        ),
        migrations.RemoveField(
            model_name="linktype",
            name="url_pattern",
        ),
        migrations.AddField(
            model_name="card",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="card",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="card",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="card",
            name="startup_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="card",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="cardtemplate",
            name="is_elite_only",
            field=models.BooleanField(default=False),
        ),
    ]
