# Generated by Django 5.2.3 on 2025-08-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("badge", models.BooleanField(default=False, help_text="Badge")),
                (
                    "font",
                    models.CharField(default="Arial", help_text="Font", max_length=50),
                ),
                (
                    "gradient",
                    models.CharField(default="", help_text="Gradient", max_length=50),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="", help_text="Background Color", max_length=50
                    ),
                ),
                (
                    "text_color",
                    models.CharField(default="", help_text="Text Color", max_length=50),
                ),
                (
                    "border_color",
                    models.CharField(
                        default="", help_text="Border Color", max_length=50
                    ),
                ),
                (
                    "border_width",
                    models.IntegerField(default=0, help_text="Border Width"),
                ),
                (
                    "border_style",
                    models.CharField(
                        default="", help_text="Border Style", max_length=50
                    ),
                ),
                (
                    "border_radius",
                    models.IntegerField(default=0, help_text="Border Radius"),
                ),
                (
                    "shadow",
                    models.CharField(default="", help_text="Shadow", max_length=50),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Card Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Card Updated At"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Link Name", max_length=50)),
                ("url", models.URLField(help_text="Link URL")),
                (
                    "icon",
                    models.CharField(default="", help_text="Link Icon", max_length=50),
                ),
                (
                    "color",
                    models.CharField(default="", help_text="Link Color", max_length=50),
                ),
                ("views", models.IntegerField(default=0, help_text="Link Views")),
                ("clicks", models.IntegerField(default=0, help_text="Link Clicks")),
            ],
        ),
    ]
